---
title: Jekyll Theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    hero title: ''
    hero body: ''
    is in navigation: false
- scope:
    path: ''
    type: team
  values:
    image: "/path/to/image"
    position: ''
env: dev
author: adropi
description: Jekyll theme
base_url: https://picitelli.github.io/jekyll-theme
assets_url: https://picitelli.github.io/jekyll-theme/assets/
url: https://picitelli.github.io/jekyll-theme
exclude:
- ".sass-cache"
- Gemfile
- Gemfile.lock
- README.md
- "*.gemspec"
sass:
  style: compressed
  sass_dir: assets/css
